name: disk-space-test
on:
  workflow_dispatch:

jobs:
  disk-space-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for the labeler
        uses: lewagon/wait-on-check-action@0179dfc359f90a703c41240506f998ee1603f9ea  #v1.0.0  
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: Team Label
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 90
      - name: Check Disk Space Before Build
        run: |
            echo "=============================================="
            echo "Checking Disk Space Before Build..."
            df -h
            xvfb-run --help
            echo "=============================================="

    #   - name: Maximize build space
    #     uses: easimon/maximize-build-space@master
    #     with:
    #         remove-codeql: 'true'
    #         remove-haskell: 'true'
    #         remove-android: 'true'
    #         remove-dotnet: 'true'
    #         remove-docker-images: 'true'
            
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
            tool-cache: false
            # all of these default to true, but feel free to set to
            # "false" if necessary for your workflow
            android: true
            dotnet: true
            haskell: true
            large-packages: true
            docker-images: true
            swap-storage: true
      - name: Check Disk Space After Action Build
        run: |
            echo "=============================================="
            echo "Checking Disk After Action and Before Build..."
            df -h
            xvfb-run --help
            echo "=============================================="

      - name: Wait for the labeler
        uses: lewagon/wait-on-check-action@v1.3.1  
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: Team Label
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 90
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Ubuntu dependencies
        run: |
          # stop relying on apt cache of GitHub runners
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev python3-venv librdkafka-dev gcc libsasl2-dev build-essential libssl-dev libffi-dev \
          librdkafka-dev unixodbc-dev libevent-dev wkhtmltopdf libkrb5-dev


      - name: Install Python dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          make install_all install_apis

      - name: Maven Clean and Build
        run: |
           echo "=============================================="
           echo "Running Maven Clean and Build..."
           echo "=============================================="
      - name: Maven build
        id: maven-build
        continue-on-error: true
        run: mvn -DskipTests clean install
      - name: Check Disk Space After Build
        run: |
          echo "=============================================="
          echo "Checking Disk Space After Build..."
          xvfb-run --help
          df -h
          apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
          xvfb-run --help
          echo "=============================================="









