#  Copyright 2021 Collate
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Update version in code freeze

on:
  workflow_dispatch:
    inputs:
        RELEASE_VERSION:
          description: "Release Version"
          required: true
        PYTHON_RELEASE_VERSION:
          description: "Provide python Release version"
          required: true
    release:
      types: [published]   

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v3

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
        # with:
        #   java-version: 11
        #   distribution: 'adopt'
        #   server-id: ossrh
        #   server-username: MAVEN_USERNAME
        #   server-password: MAVEN_PASSWORD
        #   gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        #   gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev python3-venv librdkafka-dev gcc libsasl2-dev build-essential libssl-dev libffi-dev \
          librdkafka-dev unixodbc-dev libevent-dev


      - name: Set environment variable
        run: echo "RELEASE_VERSION=${{ github.event.inputs.RELEASE_VERSION }}" >> $GITHUB_ENV

      - name: Update Version
        run: |
          mvn update_all
